#!/bin/bash
echo '++++++++++++++++++++++++++++++++++++++++++++++'
echo -e '      Action Recognition Project (Cooking)      \n                Mehdi Gorjian                  \n                  626001122                  '
echo    '++++++++++++++++++++++++++++++++++++++++++++++'

#MODEL_URL='https://drive.google.com/file/d/1V68ezH27WmSU0uAoITzemTNqE8tvM0h8/view?usp=sharing'
#LABEL_URL=https://drive.google.com/file/d/1VCa4NoTFjHTefBIzsx5RYOCVVHrBz2JM/view?usp=sharing
#VIDEO_URL_D1='https://drive.google.com/file/d/1NPF8moT1vHqpVVUDzWF9w4tPk8pa6xOg/view?usp=sharing'
#VIDEO_URL_C1=https://drive.google.com/file/d/1gdkGiOgwjlw4SL0z_nYG2kZo8CZcONyI/view?usp=sharing

echo '[INFO] cloning the repo...'


GIT_REPO_URL=https://github.com/mehdigorjian/action_recognition.git
REPO='action_recognition'
#VIDEO='drink1.mp4'

#UIN_JSON='626001122.json'
#UIN_JPG='626001122.jpg'

git clone $GIT_REPO_URL 
cd $REPO

#echo $VIDEO



mkdir model
mkdir example_clips
mkdir output


echo '[INFO] downloading necessary files...'


wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1V68ezH27WmSU0uAoITzemTNqE8tvM0h8' -O model/activity.model

wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1VCa4NoTFjHTefBIzsx5RYOCVVHrBz2JM' -O model/lb.pickle

wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1gdkGiOgwjlw4SL0z_nYG2kZo8CZcONyI' -O example_clips/cook1.mp4


echo '[INFO] prediction starting...'

python predict_video.py --model model/activity.model --label-bin model/lb.pickle --input example_clips/cook1.mp4 --output output/cooking_labeled.avi --action cooking --size 128

#cp timeLable.json $UIN_JSON
#cp timeLable.jpg $UIN_JPG